"""Initial migration

Revision ID: 419229f07f25
Revises: ff3c195d1411
Create Date: 2025-03-26 20:55:37.467993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419229f07f25'
down_revision = 'ff3c195d1411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###
