"""empty message

Revision ID: da74db9de54f
Revises: 
Create Date: 2025-03-29 23:06:23.267889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da74db9de54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('email_confirmado', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('prime_code', sa.String(length=50), nullable=True),
    sa.Column('indicador_id', sa.Integer(), nullable=True),
    sa.Column('desconto_prime', sa.Float(), nullable=True),
    sa.Column('saldo_comissoes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_email', sa.String(length=100), nullable=False),
    sa.Column('cliente_telefone', sa.String(length=20), nullable=False),
    sa.Column('cliente_endereco', sa.String(length=200), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('total_sem_desconto', sa.Float(), nullable=False),
    sa.Column('desconto_aplicado', sa.Float(), nullable=True),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=True),
    sa.Column('codigo_rastreio', sa.String(length=50), nullable=True),
    sa.Column('dados_pagamento', sa.Text(), nullable=True),
    sa.Column('codigo_prime_utilizado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prime_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('percentual_desconto', sa.Float(), nullable=False),
    sa.Column('percentual_comissao', sa.Float(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('usos_maximos', sa.Integer(), nullable=True),
    sa.Column('usos_atuais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('comissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_codigo', sa.String(length=50), nullable=False),
    sa.Column('produto_nome', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('comissoes')
    op.drop_table('prime_codes')
    op.drop_table('pedidos')
    op.drop_table('users')
    # ### end Alembic commands ###
